# assets
version: "0.3"
artifactId: "userdetails"
classifier: ''
packaging: "war"
groupId: "au.org.ala"
userdetails_war_url: "{{maven_repo_ws_url}}"

tomcat_java_opts_override: "-Xmx4g -Xms2g -XX:MaxPermSize=256m -Xss256k -XX:+UseG1GC"
